version: '2.3'
services:
  ethbase: &ethbase
    image: block.com/gethbase
    build:
      context: .
      dockerfile: execution-docker-base/Dockerfile
      args:
        CONFIG_BASE_DIR: "/basicconfig"
        DATA_DIR: "/execution"
        SOURCE_CODE: "https://github.com/orchain/go-ethereum.git"
        VERSION: main
        SYMBOL: ETH
    volumes:
      - ./basicconfig:/basicconfig 
      - ./execution:/execution
    dns:
      - 8.8.8.8

  beaconbase: &beaconbase
    image: block.com/beaconbase
    build:
      context: .
      dockerfile: consensus-docker-base/Dockerfile
      args:
        CONFIG_BASE_DIR: "/basicconfig"
        VERSION: main
        SOURCE_CODE: "https://github.com/orchain/prysm.git"
        SYMBOL: BEACON
    volumes:
      - ./basicconfig:/basicconfig
    dns:
      - 8.8.8.8
